# Generated by Django 5.0.4 on 2024-04-23 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0004_alter_like_tweet_alter_like_user_alter_tweet_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="users",
            new_name="user",
        ),
    ]
